server:
  port: 1211

spring:
  datasource:
    username: root
    password: my123456
    url: jdbc:mysql://localhost:3306/eghibli?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml